n = int(input())
i=0
saques=0
tSaques=0
bloqueios=0
tBloqueios=0
ataques=0
tAtaques=0
while i<n:
    lixo = input()
    s,b,a = input().split(' ')
    s=int(s)
    b=int(b)
    a=int(a)
    tSaques+=s
    tBloqueios+=b
    tAtaques+=a
    s,b,a = input().split(' ')
    s=int(s)
    b=int(b)
    a=int(a)
    saques+=s
    bloqueios+=b
    ataques+=a
    i+=1
print("Pontos de Saque: %.2f"%((saques/tSaques)*100),end=' %.\n')
print("Pontos de Bloqueio: %.2f"%((bloqueios/tBloqueios)*100),end=' %.\n')
print("Pontos de Ataque: %.2f"%((ataques/tAtaques)*100),end=' %.\n')